codership/documentation

- galeracluster/source/dbconfiguration.rst
http://openquery.com.au/blog/innodbflushlogsontrxcommit-galeracluster
shows why =0 is better than =2. Other examples on the same page use=0
so may as well use =0 here too.
> innodb_flush_log_at_trx_commit=0 is better than =2

- galeracluster/source/firewallsettings.rst
i tested this out. tcpdump shows the traffic like
<pre>
13:22:59.339984 IP 10.1.2.110.4567 > 239.255.102.1.4567:  wb-dop: adsl-99-15-71-204.dsl.irvnca.sbcglobal.net:3025211876<2496703007:3081009675>
13:22:59.340315 IP 10.1.2.113.4567 > 239.255.102.1.4567:  wb-dop: static.kpn.net:2972717540<3120659454:1316642428>
13:22:59.340407 IP 10.1.2.119.4567 > 239.255.102.1.4567:  wb-dop: 185.66.36.96:2972455396<3188627084:1794942693>
13:22:59.340548 IP 10.1.2.111.4567 > 239.255.102.1.4567:  wb-dop: 142.62.163.91:3038384612<3140726717:3308151976>
13:22:59.340616 IP 10.1.2.110.4567 > 239.255.102.1.4567:  wb-dop: adsl-99-15-71-204.dsl.irvnca.sbcglobal.net:3025211876<2496703007:3081009675>
</pre>
> multicast uses udp so make firewall documentation inclusive of this

- galeracluster/source/pcrecovery.rst
Mentioned on the mailing list that this is currently an error in the documentation, but might be implemented in the future. But for now, it should be removed, since it's currently causing a lot of confusion with users.
Resolves codership/documentation/issues/81
> Graceful cluster restart feature not implemented yet

- galeracluster/source/configuration.rst
* it's `innodb_flush_log_at_trx_commit` (not `innodb_flush_logs_at_trx_commit`)
* it's `default_storage_engine` (not `default-storage-engine`)
> fix a couple of typos

- galeracluster/source/detectingaslownode.rst
"wresp_local_recv_queue_avg" is typo.
"wsrep_local_recv_queue_avg" is correct parameter name.
> Fix typo at detectingaslownode.rst

- galeracluster/source/mysqlwsrepoptions.rst
Prior towsrep 25.11, wsrep_OSU_method was only a global variable. Current behavior is now consistent with MySQL behavior for variables that have both global and session scope. This means if you want to change the variable in current session you need to do it with: SET wsrep_OSU_method (without the GLOBAL keyword). Setting the variable with SET GLOBAL wsrep_OSU_method will change the variable globally but it won’t have effect on current session.
> wsrep_OSU_method is now a session variable

- galeracluster/source/installmysql.rst
Added pin to prefer galera repository over os repository even if os has newer versions.
This is the case for Ubuntu 16.04 LTS, the galeracluster.com repository contains 5.7.17~XXX, Ubuntu has 5.7.18-XXX.
> Added pin for galera repository

- galeracluster/source/installmysql.rst
According to the announcement (http://galeracluster.com/2017/07/announcing-galera-cluster-5-7-18-5-6-36-and-5-5-55-with-galera-3-21-improvements-to-ipv6-support-bug-fixes-and-changes-to-repositories-structure/) the repos are hosted at releases.galeracluster.com not releases.codership.com
> Fixed wrong URL for DEB-Repos

- galeracluster/source/galerastatusvariables.rst
cluster weight
codership/galera#496
codership/galera#501
Added new status variables
- wsrep_open_connections: Number of open connection objects in
Galera provider. This is indicates number of concurrent TOI
operations run locally.
- wsrep_open_transaction: Number of concurrently running local
transactions
- wsrep_cluster_weight: Total weight of the current cluster.
> Added new status variables for open connections, transactions,

- galeracluster/source/documentation/galera-parameters.rst
- release-notes/release-notes-galera-25.3.29.txt
- release-notes/release-notes-mysql-wsrep-5.6.47-25.29.txt
- release-notes/release-notes-mysql-wsrep-5.7.29-25.21.txt
- Release notes
- Documented new Galera configuration option socket.send_buf_size and
default change for socket.recv_buf_size.
> Release notes for Galera 3.29, MySQL-wsrep 5.6.47-25.29, 5.7.29-25.21.

- galeracluster/source/_static/codership.css
- galeracluster/source/_templates/layout.html
- galeracluster/source/faq.rst
The glossary links are now in shades of purple.
> Glossary link colors adjusted.

- galeracluster/source/documentation/ssl-cert.rst
> Issue #252

- galeracluster/source/documentation/mysql-wsrep-options.rst
Fixes codership/documentation#303
> Value 'events' is not valid for variable wsrep_trx_fragment_unit

- galeracluster/source/_static/codership.css
Link color changed to c7a049.
To see the result, see wsrep_cluster_address in Wsrep Options
> Issue #342

- galeracluster/source/faq.rst
Remove wrong statement about Galera supporting snapshot
isolation. Also, replace "multi-master" with "multi-primary" and
and "multi-master conflicts" with "cluster-wide conflicts".
> Remove SNAPSHOT ISOLATION mention from FAQ page

- galeracluster/source/training/tutorials/supporting-transaction-isolation-levels.rst
Remove confusing/contradictory statements about Galera (partially)
supporting SNAPSHOT ISOLATION from page
`supporting-transaction-isolation-levels.rst`.
> Remove mentions of SNAPSHOT ISOLATION

- galeracluster/source/documentation/crash-recovery.rst
Improve explanation around `mysql --wsrep-recover` and mention helper script `wsrep_recover`.
Also, script `mysqld_bootstrap` does not take any arguments. Replace `mysqld_bootstrap --wsrep-new-cluster` with `mysqld_bootstrap`.
Fixes codership/documentation#368
> Mention wsrep_recover script in crash recovery page

- galeracluster/source/documentation/mysql-wsrep-options.rst
Added details on the wsrep_forced_binlog_format being effective for DML operations only. Also mentioned that binlog_format is deprecated.
> Issue #428

- galeracluster/source/documentation/galera-status-variables.rst
fixed a long standing typo that was reported to us
commit 3aa145fed180f62aabe6995402f9e2b49886c8b4
Author: kennethpjdyer <kenneth@avoceteditors.com>
Date:   Sat Jan 10 22:19:15 2015 -0500
Ref #38: Updates to Reference section.  Alphabetized table and reference entires.  Updated formatting on default/example column from italics to monospace.  Changed indexing for galerastatusvariables from 'parameters' to 'status variables'.
> s/wsrep_certs_index_size/wsrep_cert_index_size/g - thanks for the bug report

- galeracluster/source/kb/gaps-in-gtid-sequence-numbers.rst
- galeracluster/source/kb/index.rst
A new troubleshooting article added for GTID gaps in binlog.
> Issue #493 -  GTID gaps in binlog

- galeracluster/source/documentation/galera-parameters.rst
According to Galera code the correct default value is 64500. Change
documentation accordingly.
> Fix gcs.max_packet_size default value

- galeracluster/source/documentation/galera-parameters.rst
Description of gcache recovery added. The default value of gcache.recover is now "yes".
> Issue #523 - gcache.recover updated

- galeracluster/source/documentation/mysql-wsrep-options.rst
plugin-wsrep-provider added.
If this is ok, what shall we do with the numerous references to wsrep_provider_options? Such as:
- You can configure the parameters of Auto-Eviction by setting the following options through wsrep_provider_options...
- All wsrep_provider_options settings need to be specified on a single line. In case of multiple instances of wsrep_provider_options, only the last one is used.
Should we refer to plugin-wsrep-provider instead, as it is ON by default?
> Issue #439

- galeracluster/source/documentation/galera-parameters.rst
Added a note that exceeding the maximum value of repl.max_ws_size may prevent the node from starting up
> repl.max_ws_size - Issue #555
