galeracluster/source/certificationbasedreplication.rst

Fixed a couple of missing characters, one grammar edit

minor typo editing

---

galeracluster/source/introduction.rst

Minor Typo Fix

---

galeracluster/source/firewallsettings.rst
galeracluster/source/iptables.rst
galeracluster/source/pf.rst

Hi Kenneth, Dan has added info about configuring firewall for using UDP multicast. I reworded it slightly. Could you please check it and merge if it is good. Or provide your own variant. Thanks, Alex.

References codership/documentation#56 reworded Dan's UDP text.

---

galeracluster/source/gettingstarted.rst

Fix minor typo in gettingstarted.rst

---

galeracluster/source/statetransfer.rst

Fix minor typo in statetransfer.rst

---

galeracluster/source/galerainstallation.rst

Fix minor typo in galerainstallation.rst

---

galeracluster/source/installmariadbsrc.rst

Fix minor typo in installmariadbsrc.rst

---

galeracluster/source/restartingcluster.rst

Fixed couple of typos and removed duplicate paragraphs conveying the same information.
Please, review :)

Fix typos and remove duplicate in restartingcluster.rst

---

galeracluster/source/monitoringthecluster.rst

wsrep_ready values should be ON/OFF, not TRUE/FALSE.

fix for documentation error

---

galeracluster/source/installmysql.rst

missing back slash

---

galeracluster/source/galerainstallation.rst
galeracluster/source/glb.rst
galeracluster/source/glbparameters.rst
galeracluster/source/installmysql.rst
galeracluster/source/loadbalancing.rst
galeracluster/source/mysqlwsrepoptions.rst
galeracluster/source/reference.rst

Merge with master to update the website.  Additions in this release:
- Documents configuration and use of Galera Load Balancer.
- Add reference page for Galera Load Balancer configuration parameters and arguments.
- Removed Postfix section from galerainstallation, as obsolete.
- Added CentOS MySQL compatibility library upgrade section to installmysql.

Web Update

---

galeracluster/source/firewalld.rst
galeracluster/source/firewallsettings.rst
galeracluster/source/installxtradbsrc.rst
galeracluster/source/iptables.rst
galeracluster/source/mysqlwsrepoptions.rst
galeracluster/source/reference.rst
galeracluster/source/scriptablesst.rst
galeracluster/source/versioninginformation.rst
galeracluster/source/xtrabackupoptions.rst

Merges draft into master for web update.  Changes include:
- Documentation for FirewallD
- Configuration page for XtraBackup.

Merge with Master for Web Update

---

galeracluster/source/conf.py
galeracluster/source/configurationtips.rst
galeracluster/source/gettingstarted.rst
galeracluster/source/glossary.rst
galeracluster/source/index.rst
galeracluster/source/mysqlwsrepfunctions.rst
galeracluster/source/mysqlwsrepoptions.rst
galeracluster/source/reference.rst
galeracluster/source/schemaupgrades.rst
galeracluster/source/whatsnew.rst

Update includes new docs for NBO, initial entry in a What's New section for 4.x, and the initial docs for wsrep Functions.

Merge Draft work into 4.x Staging Branch

---

galeracluster/source/galeraparameters.rst
galeracluster/source/galerastatusvariables.rst

Add documentation for gcomm.thread_prio and wsrep_desync_counter.

Website Update

---

galeracluster/source/glossary.rst
galeracluster/source/mysqlwsrepoptions.rst
galeracluster/source/schemaupgrades.rst
galeracluster/source/streamingreplication.rst
galeracluster/source/technicaldescription.rst
galeracluster/source/userguide.rst
galeracluster/source/usingsr.rst
galeracluster/source/whatsnew.rst

Merges 4.x-staging with the current state of the draft branch and adds documentation for Streaming Replication.

Merge for Streaming Replication Docs

---

galeracluster/source/mysqlwsrepfunctions.rst
galeracluster/source/mysqlwsrepoptions.rst
galeracluster/source/schemaupgrades.rst
galeracluster/source/streamingreplication.rst
galeracluster/source/usingsr.rst
galeracluster/source/whatsnew.rst

Minor update to introduce index directives for 4.x updates.

Adds indexing directives for 4.x features.

---

galeracluster/source/sslconfig.rst

really simple change, changed Gelera to Galera

noticed + fixed a typo

---

release-notes/release-notes-galera-25.3.22.txt
release-notes/release-notes-mysql-wsrep-5.5.57-25.22.txt
release-notes/release-notes-mysql-wsrep-5.6.37-25.21.txt
release-notes/release-notes-mysql-wsrep-5.7.19-25.13.txt

Release notes for Galera 25.3.22, MySQL-wsrep versions 5.5.57-25.22,

---

galeracluster/source/galerastatusvariables.rst

Fixed copy-paste error in wsrep_cluster_weight documentation.

codership/galera#518 Fixed wsrep_cluster_weight documentation

---

galeracluster/source/galeraparameters.rst

Refs codership/galera-bugs#181

Added description of the `cert.optimistic_pa` parameter.

---

galeracluster/source/documentation/ssl-sst.rst
galeracluster/source/documentation/sst-physical.rst
galeracluster/source/documentation/sst.rst

Added description of `clone` SST method

---

galeracluster/source/kb/index.rst

Use cases added. Issue #130.

---

galeracluster/source/documentation/auto-eviction.rst
galeracluster/source/documentation/galera-parameters.rst

First changes to evs.version info implemented.

Issue #175

---

galeracluster/source/documentation/administration.rst
galeracluster/source/documentation/backup-cluster.rst
galeracluster/source/documentation/firewall-settings.rst
galeracluster/source/documentation/galera-parameters.rst
galeracluster/source/documentation/glossary.rst
galeracluster/source/documentation/monitoring-cluster.rst
galeracluster/source/documentation/mysql-wsrep-options.rst
galeracluster/source/documentation/node-provisioning.rst
galeracluster/source/documentation/node-states.rst
galeracluster/source/documentation/quorum-reset.rst
galeracluster/source/documentation/scriptable-sst.rst
galeracluster/source/documentation/ssl-sst.rst
galeracluster/source/documentation/sst-logical.rst
galeracluster/source/documentation/sst-physical.rst
galeracluster/source/documentation/sst.rst
galeracluster/source/documentation/state-transfer.rst
galeracluster/source/documentation/technical-description.rst
galeracluster/source/documentation/upgrading.rst
galeracluster/source/documentation/weighted-quorum.rst
galeracluster/source/documentation/xtrabackup-options.rst
galeracluster/source/editors/faqs-pending.rst
galeracluster/source/faq.rst
galeracluster/source/kb/index.rst
galeracluster/source/kb/requested-state-transfer-failed.rst
galeracluster/source/training/tutorials/debug-problems-with-sst.rst
galeracluster/source/training/tutorials/galera-backup.rst
galeracluster/source/training/tutorials/sst-or-not.rst
galeracluster/source/training/tutorials/testing-cluster.rst
galeracluster/source/training/videos/galera-backup-exercises.rst

New glossary items added. Issue #124.

---

galeracluster/source/documentation/index.rst
galeracluster/source/documentation/mariadb-options.rst

Mariadb options

---

galeracluster/source/documentation/mariadb-options.rst

Also, the server options are now in alphabetical order.

Issue #254. Added a note that this is an optional feature.

---

galeracluster/source/documentation/mysql-wsrep-options.rst

The option was added for your review.

Issue #192. wsrep_recover option was added.

---

galeracluster/source/faq.rst

Add missing word

---

galeracluster/source/documentation/mysql-wsrep-options.rst
galeracluster/source/training/tutorials/starting-cluster.rst

New commands added for Colin to check.

Issue #187. Starting commands for MariaDB and XDB were added.

---

galeracluster/source/documentation/galera-parameters.rst
galeracluster/source/documentation/index.rst
galeracluster/source/documentation/ldap-plugin.rst

Using LDAP plugin added for review.
One indexing error corrected.

Issue #270

---

galeracluster/source/documentation/audit-log-plugin.rst
galeracluster/source/documentation/index.rst

First draft of how to use the AUDIT plugin.
Can you check for content, I'll check for layout.

Issue #271, audit plugin

---

galeracluster/source/documentation/galera-status-variables.rst

Typo fixed.

---

galeracluster/source/documentation/galera-parameters.rst

Issue #279

---

galeracluster/source/documentation/crash-recovery.rst
galeracluster/source/documentation/ldap-plugin.rst
galeracluster/source/documentation/mariadb-options.rst
galeracluster/source/documentation/pam-plugin.rst
galeracluster/source/documentation/ssl-sst.rst

Also contains a number of compilation fixes, most notably - fixes rendering of ldap plugin option table.

Document new way of SSL configuration for SST

---

galeracluster/source/documentation/galera-parameters.rst
galeracluster/source/documentation/galera-status-variables.rst
release-notes/release-notes-galera-25.3.34.txt
release-notes/release-notes-galera-26.4.9.txt
release-notes/release-notes-mysql-wsrep-5.7.34-25.26.txt
release-notes/release-notes-mysql-wsrep-8.0.25-26.7.txt

- Document wsrep_apply_waits status variable
- Release notes for Galera 3.34, 4.9 and MySQL-wsrep 5.7.34, 8.0.25

Document wsrep_apply_waits, release notes

---

galeracluster/source/documentation/install-mysql.rst

update ubuntu install guidelines

Update ubuntu guidelines

---

galeracluster/source/documentation/firewalld.rst
galeracluster/source/documentation/galera-manager.rst
galeracluster/source/documentation/galera-status-variables.rst
galeracluster/source/documentation/install-mysql.rst
galeracluster/source/documentation/load-balancing.rst
galeracluster/source/documentation/log.rst
galeracluster/source/documentation/overview.rst
galeracluster/source/documentation/recovery.rst
galeracluster/source/documentation/tech-desc-introduction.rst
galeracluster/source/documentation/upgrading.rst
galeracluster/source/documentation/weighted-quorum.rst
galeracluster/source/faq.rst
galeracluster/source/kb/two-node-clusters.rst

Test to fix an incorrect link to banner.

---

galeracluster/source/training/courses/index.rst

Training dates updates as requested by Sakari

Training dates updated.

---

galeracluster/source/documentation/jails.rst

Added info on installing Galera Cluster on FreeBSD from a binary package.

Issue #286

---

galeracluster/source/documentation/install-mysql-src.rst
galeracluster/source/documentation/managing-fc.rst
galeracluster/source/documentation/mysql-wsrep-options.rst

A test to get the banner on PDF.

---

galeracluster/source/documentation/galera-parameters.rst

Issue #305

---

galeracluster/source/documentation/galera-parameters.rst
galeracluster/source/documentation/inconsistency-voting.rst
galeracluster/source/documentation/index.rst
galeracluster/source/documentation/mariadb-options.rst
galeracluster/source/documentation/mysql-wsrep-options.rst

A new topic Inconsistency Voting added.
A test conversion.

Issue #144

---

galeracluster/source/documentation/ssl-sst.rst

Option value should be `DISABLED`, not `DISABLE`

Fix typo in setting ssl-mode

---

galeracluster/source/documentation/mysql-wsrep-options.rst

Use MySQL-wsrep and MariaDB versions for Initial Version
and Deprecated Version.

Fix mysql-wsrep-options versioning

---

galeracluster/source/training/tutorials/galera-installation.rst

Minimum requirements updated, info on recommended hardware added.

Issue #310

---

galeracluster/source/documentation/galera-manager-adding-clusters.rst
galeracluster/source/documentation/galera-manager-adding-nodes.rst
galeracluster/source/documentation/galera-manager-adding-users.rst
galeracluster/source/documentation/galera-manager-initializing-data.rst
galeracluster/source/documentation/galera-manager-monitoring-clusters.rst
galeracluster/source/documentation/galera-manager-ports.rst
galeracluster/source/documentation/gmd-install.rst

Image width reduced from 800 -> 600
First test to see if this helps.

Issue #317 - Fix image width in PDF

---

galeracluster/source/documentation/galera-parameters.rst
galeracluster/source/documentation/galera-status-variables.rst
galeracluster/source/documentation/mysql-wsrep-options.rst
galeracluster/source/documentation/xtrabackup-options.rst

Issue #319

---

galeracluster/source/documentation/galera-parameters.rst
galeracluster/source/documentation/galera-status-variables.rst

- gcache.freeze_purge_at_seqno documented in Galera parameters
- wsrep_ist_receive_status documented in Galera Status parameters

Issue #262

---

galeracluster/source/training/tutorials/migrate.rst
galeracluster/source/training/tutorials/migration.rst

changing the nomenclature, considering we did this in MySQL 8.0.26

No more master-slave but primary-replica

---

galeracluster/source/documentation/install-xtradb-src.rst

this is percona related, why does it say anything about mariadb?

we don't need mariadb

---

galeracluster/source/documentation/glossary.rst
galeracluster/source/documentation/mariadb-options.rst
galeracluster/source/documentation/mysql-wsrep-options.rst
galeracluster/source/documentation/schema-upgrades.rst

Issue #237

---

galeracluster/source/documentation/monitoring-cluster.rst
galeracluster/source/documentation/mysql-wsrep-options.rst
galeracluster/source/editors/style-guide.rst
galeracluster/source/kb/index.rst
galeracluster/source/kb/parallel-applier-threads.rst
galeracluster/source/training/tutorials/galera-monitoring.rst
galeracluster/source/training/tutorials/galera-on-aws.rst
galeracluster/source/training/videos/galera-mariadb-installing-examples.rst
galeracluster/source/training/videos/galera-mysql-installing-examples.rst

wsrep_applier_threads recommended instead of wsrep_slave_threads.

Issue #331

---

galeracluster/source/documentation/mysql-wsrep-options.rst

innodb-wsrep-applier-lock-wait-timeout added for review.

Issue #335

---

release-notes/release-notes-galera-25.3.36.txt
release-notes/release-notes-galera-26.4.11.txt
release-notes/release-notes-mysql-wsrep-5.7.36-25.28.txt
release-notes/release-notes-mysql-wsrep-8.0.27-26.9.txt

Add release notes for Galera 25.3.36, 26.4.11 and MySQL 5.7.36 and MySQL

---

galeracluster/source/documentation/auto-eviction.rst
galeracluster/source/documentation/glb.rst
galeracluster/source/documentation/schema-upgrades.rst

Issue #351

---

galeracluster/source/documentation/mysql-wsrep-options.rst

Issue #330

---

galeracluster/source/documentation/sst-physical.rst

Refs codership/documentation#358

Add info how to setup MySQL account for xtrabackup- and clone-based SSTs

---

galeracluster/source/documentation/galera-parameters.rst

The descriptions were clarified for the following parameters:
gmcast.peer_timeout
gmcast.time_wait
pc.announce_timeout
pc.checksum
pc.linger
pc.npvo
pc.wait_prim
pc.wait_prim_timeout
pc.weight
repl.causal_read_timeout
socket.ssl_cipher
Mark the following parameters deprecated:
protonet.backend
protonet.version
socket.ssl_compression

Improve documentation for various Galera parameters

---

galeracluster/source/documentation/mariadb-options.rst

Issue #369

---

galeracluster/source/_templates/layout.html

Also added the &copy; tag to have the copyright logo

Change copyright notice to 2023 for docs

---

galeracluster/source/documentation/install-mysql.rst

This isn't final, but at least it gets people started to MySQL 8 even

Fix install docs

---

galeracluster/source/documentation/galera-status-variables.rst

variable.
Refs codership/documentation#407

Add version 11 to the description of wsrep_protocol_version status

---

galeracluster/source/documentation/mysql-wsrep-options.rst

wsrep_applier_FK_failure_retries added to the options table

Issue #406

---

galeracluster/source/documentation/mariadb-options.rst
galeracluster/source/training/tutorials/index.rst

A link and an abstract added to Tutorials page.

Return the limitations page

---

galeracluster/source/documentation/galera-parameters.rst

Added a warning not to change the default value.

Issue #390

---

galeracluster/source/documentation/mysql-wsrep-options.rst

Issue #384

---

galeracluster/source/documentation/mariadb-options.rst

Issue #412

---

galeracluster/source/documentation/mysql-wsrep-options.rst

Issue #386

---

galeracluster/source/documentation/mysql-wsrep-options.rst

Variable description and default value edited.

---

galeracluster/source/documentation/install-xtradb.rst

Installation instructions updated.
See https://github.com/codership/documentation/issues/392.

Pxc bin installation

---

galeracluster/source/documentation/system-tables.rst

A note on PERFORMANCE_SCHEMA.PROCESSLIST and examples were added.

Issue #405

---

galeracluster/source/documentation/galera-status-variables.rst

"To see retrieve..." replaced by "To retrieve..."

Issue #422

---

galeracluster/source/documentation/mysql-wsrep-options.rst

wsrep_certification_rules marked as deprecated.

Issue #433

---

galeracluster/source/documentation/galera-parameters.rst

Issue #434

---

galeracluster/source/documentation/mysql-wsrep-options.rst
galeracluster/source/documentation/schema-upgrades.rst

Added examples of session-based method changes. Fixed one rst problem, which caused one option to appear in an incorrect place in the table.

Issue #418

---

galeracluster/source/documentation/system-tables.rst

Issue #441

---

galeracluster/source/documentation/sst-physical.rst

The default value for SST methods for 8.4.2 has been indicated.

Issue #440

---

galeracluster/source/training/tutorials/galera-monitoring.rst

Instructions on reading gra log files added.

Issue #304

---

galeracluster/source/documentation/index.rst
galeracluster/source/documentation/mysql-wsrep-options.rst
galeracluster/source/documentation/utility-scripts.rst

Issue #374

---

galeracluster/source/documentation/backup-cluster.rst

Content updated in line with the ticket instructions.

Issue #139

---

galeracluster/source/documentation/sst-physical.rst

Issue #341

---

galeracluster/source/documentation/scriptable-sst.rst
galeracluster/source/documentation/sst-physical.rst

Progress reporting documented.

Issue #334

---

galeracluster/source/documentation/index.rst
galeracluster/source/documentation/mariabackup-options.rst
galeracluster/source/documentation/mysql-wsrep-options.rst
galeracluster/source/documentation/xtrabackup-options.rst

Mariabackup added. The cpat option description updated.

Issue #227

---

galeracluster/source/documentation/galera-parameters.rst

Issue #129

---

galeracluster/source/training/tutorials/index.rst
galeracluster/source/training/tutorials/recovery-on-ansible.rst

Issue #282

---

galeracluster/pasture/source/index.rst
galeracluster/source/documentation/docker.rst
galeracluster/source/documentation/install-mariadb-src.rst
galeracluster/source/documentation/install-mysql-src.rst
galeracluster/source/documentation/install-mysql.rst
galeracluster/source/documentation/log.rst
galeracluster/source/documentation/mysql-wsrep-options.rst
galeracluster/source/documentation/sst-logical.rst
galeracluster/source/documentation/state-transfer.rst
galeracluster/source/documentation/upgrading.rst
galeracluster/source/training/tutorials/configuration.rst
galeracluster/source/training/tutorials/getting-started-docker.rst

Version updates. Also some links updated.

Issue #454

---

galeracluster/source/documentation/mysql-wsrep-options.rst

Issue #471

---

galeracluster/source/documentation/install-mysql.rst

Added links to disabling SELinux and AppArmor.

Issue #287

---

galeracluster/source/documentation/gmd-install.rst

Supported OS versions updated.

Issue #410

---

galeracluster/source/documentation/mariadb-options.rst

Option marked as deprecated and removed. Added a link to the replacing option.

Issue #480

---

galeracluster/source/training/tutorials/testing-cluster.rst

Layout fixed. Grammatical errors corrected.

Issue #485

---

galeracluster/source/documentation/galera-status-variables.rst

Issue #487

---

galeracluster/source/documentation/galera-status-variables.rst

It has been emphasized that this is an average value.

Issue #497

---

galeracluster/source/documentation/mysql-wsrep-options.rst

Issue #482 - resolving a conflict

---

galeracluster/source/documentation/mysql-wsrep-options.rst

Issue #463

---

galeracluster/source/documentation/administration.rst

Fixing the git conflict in PR #312

Issue #311, PR #312

---

galeracluster/source/documentation/mariadb-options.rst

Initial versions updated.
Language check.

Fix MariaDB options - Issue #509

---

galeracluster/source/documentation/galera-parameters.rst

Remove sync_binlog - Issue #511

---

galeracluster/source/documentation/galera-parameters.rst

Issue #518 - gmcast.isolate

---

galeracluster/source/documentation/galera-parameters.rst

_pc.linger_ default fixed. Examples of _base_dir_ added.

Issue #526 - pc.linger default value is now PT20S

---

galeracluster/source/documentation/selinux.rst

Corrections made in line with pull request 197

Fix SELinux - Issue #503

---

galeracluster/source/kb/illegal-mix-of-collations.rst
galeracluster/source/kb/index.rst

A troubleshooting article was added

Issue #266

---

galeracluster/source/documentation/deployment.rst
galeracluster/source/documentation/install-mariadb-src.rst
galeracluster/source/documentation/install-mysql-src.rst
galeracluster/source/documentation/install-xtradb-src.rst
galeracluster/source/documentation/install.rst
galeracluster/source/documentation/versioning-information.rst
galeracluster/source/training/tutorials/galera-installation.rst
galeracluster/source/training/tutorials/getting-started.rst

Notes on FreeBSD support added.

FreeBSD up to 5.7 - Issue #529

---

galeracluster/source/documentation/mysql-wsrep-options.rst
galeracluster/source/documentation/sst.rst

All SST methods listed.

---

galeracluster/source/documentation/mariadb-options.rst

wsrep_replicate_myisam added to MariaDB Options

---

galeracluster/source/documentation/galera-parameters.rst
galeracluster/source/documentation/mariadb-options.rst

datadir moved to MariaDB options

Move datadir to MariaDB options - Issue #536

---

galeracluster/source/training/tutorials/migration.rst

A note on manually changing the database engine added.

Migration - Issue #207

---

galeracluster/source/documentation/install-mariadb-src.rst

MariaDB not in beta - Issue #467

---

galeracluster/source/conf.py

Attempt to remove blank pages from the PDF layout

Remove blank pages - Issue #110

---

galeracluster/source/documentation/upgrading.rst

A note on protocol version changes added.

Protocol change with rolling upgrade - Issue #543

---

galeracluster/source/documentation/install-mysql.rst
galeracluster/source/documentation/security.rst

Mentioned that SSL covers IST, too. Typos fixed.

SSL-IST: Issue #545

---

galeracluster/source/documentation/galera-status-variables.rst

Status variables wsrep_cluster_capabilities and wsrep_provider_capabilities added.
Descriptions provided by @ayurchen.

Issue #548 - add missing status variables

---

galeracluster/source/documentation/arbitrator.rst

Update garbd SSL instructions - Issue #552
